version: '3'
services:
  dotfiles:
    build:
      context: .
      dockerfile: Dockerfile
    image: auek/dotfiles:latest
    container_name: dotfiles
    volumes:
      - ./.dotfiles:/home/devuser/.dotfiles
    # Keep container running
    tty: true
    stdin_open: true
