---
- name: System setup tasks
  become: true
  block:
    - name: Including apt tasks
      ansible.builtin.include_tasks: apt.yml
    - name: Set zsh as shell
      ansible.builtin.user:
        name: devuser
        shell: /bin/zsh
