---
- name: System setup tasks
  become: true
  block:
    - name: Include package variables
      ansible.builtin.include_vars:
        file: vars/packages.yml

    - name: Install common packages
      ansible.builtin.package:
        name: "{{ system_common_packages }}"
        state: present

    - name: Install optional packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ system_optional_packages }}"
      register: optional_install
      failed_when: false

    - name: Report failed optional package installations
      ansible.builtin.debug:
        msg: "Optional package {{ item.item }} could not be installed"
      loop: "{{ system_optional_install.results }}"
      when: item.failed is defined and item.failed

    - name: Set zsh as shell
      ansible.builtin.user:
        name: devuser
        shell: /bin/zsh
