- name: Download NVM installation script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh"
    dest: "/tmp/nvm-install.sh"
    mode: '0755'
  become: false
  vars:
    nvm_version: "0.40.1"

- name: Execute NVM installation script
  ansible.builtin.shell:
    cmd: bash /tmp/nvm-install.sh
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  args:
    executable: /bin/bash
  become: false
