---
- name: Download Oh My Zsh installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
    mode: "0644"

- name: Run Oh My Zsh installation script
  ansible.builtin.command: sh /tmp/install_ohmyzsh.sh --unattended --keep-zshrc
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  changed_when: ohmyzsh_result.rc == 0

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: v0.7.1
