- name: Install Node using NVM
  ansible.builtin.shell:
    cmd: |
      source ~/.zprofile && nvm install node --lts 2>&1
    executable: /bin/zsh
  register: nvm_result
  changed_when: >
    'is already installed' not in nvm_result.stdout
    and 'is already installed' not in nvm_result.stderr
  become: false
