all:
	stow --verbose --target=/home/devuser/ --restow zshrc
	stow --verbose --target=/home/devuser/ --restow tmux
delete:
	stow --verbose --target=/home/devuser/ --delete zshrc
	stow --verbose --target=/home/devuser/ --delete tmux
