all:
	stow --verbose --target=$$HOME --restow zshrc
	stow --verbose --target=$$HOME --restow zprofile
	stow --verbose --target=$$HOME --restow tmux
	stow --verbose --target=$$HOME --restow nvim
	stow --verbose --target=$$HOME --restow aider
delete:
	stow --verbose --target=$$HOME --delete zshrc
	stow --verbose --target=$$HOME --delete zprofile
	stow --verbose --target=$$HOME --delete tmux
	stow --verbose --target=$$HOME --delete nvim
	stow --verbose --target=$$HOME --delete aider
