- name: Setup
  hosts: localhost

  tasks:
    - name: Install packages with apt
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - tmux
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Clone nvim repository
      git:
        repo: https://github.com/neovim/neovim
        dest: "{{ ansible_env.HOME }}/src/nvim"
        clone: true
        version: stable

    - name: Install nvim build dependencies
      become: true
      apt:
        name:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
        state: present

    - name: Build nvim release version
      community.general.make:
        chdir: "{{ ansible_env.HOME }}/src/nvim"
        params:
          CMAKE_BUILD_TYPE: Release

    - name: Install nvim release version
      become: true
      community.general.make:
        chdir: "{{ ansible_env.HOME }}/src/nvim"
        target: install
