- name: Setup dev environment
  hosts: localhost
  tasks:
    - name: Install packages and shell
      become: true
      block:
        - name: Including apt tasks
          ansible.builtin.include_tasks: tasks/apt.yml
        - name: Set zsh as shell
          ansible.builtin.user:
            name: devuser
            shell: /bin/zsh
    - name: Ensure .config directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
        mode: "0755"

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'
      become: false
    - name: Stow dotfiles
      ansible.builtin.command:
        argv: ["make"]
        chdir: "{{ ansible_env.HOME }}/.dotfiles/"
      register: stow_result
      changed_when: stow_result.stdout != ''
    - name: Include ohmyzsh tasks
      ansible.builtin.include_tasks: tasks/ohmyzsh.yml
    - name: Include nvim tasks
      ansible.builtin.include_tasks: tasks/nvim.yml
    - name: Include nvm tasks
      ansible.builtin.include_tasks: tasks/nvm.yml
    - name: Include node tasks
      ansible.builtin.include_tasks: tasks/node.yml
