- name: Setup dev environment
  hosts: localhost
  tasks:
    - block:
        - name: Install with apt
          include_tasks: tasks/apt.yml
        - name: Set zsh as shell
          ansible.builtin.user:
            name: devuser
            shell: /bin/zsh
      become: true
    - name: Stow dotfiles
      command: "chdir={{ ansible_env.HOME }}/.dotfiles make"
    - name: Install Oh My Zsh
      include_tasks: tasks/ohmyzsh.yml
    - name: Build nvim from source
      include_tasks: tasks/nvim.yml
