---
- name: Setup dev environment
  hosts: localhost
  roles:
    - role: system
      tags:
        - system
        - full
        - slim
    - role: dotfiles
      tags:
        - dotfiles
        - full
        - slim
    - role: shell
      tags:
        - shell
        - full
        - slim
    - role: development
      tags:
        - development
        - full
